name: Deploy with Helm

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Lint chart
        run: helm lint .

      - name: Dry run deploy
        run: |
          helm upgrade --install myapp . \
            -f values-prod.yaml \
            --dry-run --client